[package]
name = "icp_token_wallet"
version = "0.1.0"
edition = "2024"

[dependencies]
candid = "0.10.13"
ic-cdk = "0.17.1"
ic-cdk-macros = "0.17.1"
serde = "1.0.218"
serde_json = "1.0.139"


[lib]
crate-type = ["cdylib"]